    - name: Install mysql and dependencies
      apt:
        name:
         - mysql-server
         - mysql-client
         - python-mysqldb
         - python-pymysql
        state: present
    - name: start mysql server
      service:
         name: mysql
         state: restarted
    - name: Make sure a service is running
      command: service mysql start
    - name: Create a new MySQl DB.
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{mysql_db_name}}"
        state: present
    - name: create a user in the DB.
      mysql_user:
        name: "{{mysql_db_user_name}}"
        password: "{{mysql_root_password}}"
        priv: "*.*:ALL"
        state: present
        host: '%'
    - name: Get MySQL version with non-default credentials
      mysql_info:
        login_user: "{{mysql_db_user_name}}"
        login_password: "{{mysql_root_password}}"
        filter: version
