    - name: Install Flask and its dependecy.
      pip:
        name:
          - flask
          - flask-mysql
        state: latest
    - name: copy the source code
      copy:
        src: app.py
        dest: /opt/app.py
    - name: Start the web server.
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
